name: Autorun Python Script

on:
  # Schedule trigger (runs daily at 5:00 AM UTC)
  schedule:
    - cron: '0 5 * * *'

  # Manual trigger
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x  # Replace with your preferred Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium  # Install selenium
          pip install -r requirements.txt || true  # Optional: Install from requirements.txt if present

      # Step 4: Run the Python script
      - name: Run Python script
        run: |
          python __init__.py
