name: Autorun Python Script

on:
  schedule:
    - cron: '0 5 * * *' # Schedule to run at 5:00 AM UTC
  workflow_dispatch: # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium openpyxl
          pip install -r requirements.txt || true

      # Step 4: Install Google Chrome and ChromeDriver
      - name: Install Google Chrome and ChromeDriver
        run: |
          # Install dependencies for Google Chrome
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f  # Install any missing dependencies

          # Install ChromeDriver
          CHROME_VERSION=$(google-chrome-stable --version | sed 's/Google Chrome //')
          DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          wget https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      # Step 5: Verify installed dependencies
      - name: Verify dependencies
        run: |
          python -m pip list

      # Step 6: Run the Python script
      - name: Run Python script
        run: |
          python __init__.py
